### ISSUE TITLE
Combination of -g and --grid does not work for multiple images

### ISSUE THREAD

**Issue by xeruf** [hzeller/timg#64] opened 2021-11-05 15:10 UTC
Konsole:
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/13354331/140532631-84baf81e-d576-4db5-b685-d88515af3ff6.png">
As you can see, each parameter works alone, but there is some weird interlacing in combination.

Kitty:
<img width="1863" alt="image" src="https://user-images.githubusercontent.com/13354331/140532778-561e41db-db49-4247-9a24-c46f486e16ac.png">
In Kitty, every second image is simply omitted.

**Comment by xeruf** [comment] 2021-11-05 15:12
Amendment: This is due to the absurdly high width I give it because I want to only limit the height.
In Konsole, this wraps the lines.
In Kitty, they are cut off.

**Comment by hzeller** [comment] 2021-11-30 20:41
With the new feature to only partially give the geometry, this will help to automatically fill the available width of the terminal while you still can limit the height; here, we only give the height (the `-g` option gets an empty value before the `x`):

```
timg --grid=2x1 -gx12 *.png
```

**Comment by hzeller** [comment] 2021-12-25 20:01
I think this one can be closed as the original issue was caused by providing a very very wide terminal geometry (resulting in wrapping characters). The intended behavior can now be achieved with the partial terminal size feature mentioned above.

**Closed by hzeller** 2021-12-25 20:01 UTC
