### ISSUE TITLE
Respect SVG transparency

### ISSUE THREAD

**Issue by xeruf** [hzeller/timg#77] opened 2022-02-09 10:20 UTC
When viewing an SVG image, a white background is added. This is probably due to the default of ImageMagick which can be changed with the flag `-background none` :)

**Comment by hzeller** [comment] 2022-02-10 16:55
We need to find how we can tell the API to background fill with `none` like the convert commandline does.

**Comment by acxz** [comment] 2022-04-13 18:21
Maybe take a look at how [icat](https://github.com/atextor/icat) does it?

icat on top, timg on bottom:
![icatvtimg](https://user-images.githubusercontent.com/17132214/163245056-3f5994e4-a192-46e7-a4fd-d444aa149182.png)

Ignore the scaling issue, icat doesn't properly scale images to the original aspect ratio.

**Comment by hzeller** [comment] 2022-04-13 18:38
Looks like that program is using imlib2 . Can it read SVGs ?
Might be worthwhile experimenting with.

**Comment by acxz** [comment] 2022-04-13 19:33
Actually did some digging into the timg codebase and honestly its just this fix right here:

https://github.com/hzeller/timg/blob/26b58c052fe62b1bc945fec8d114a8996871c4b3/src/framebuffer.cc#L44

```
- return {(uint8_t)r, (uint8_t)g, (uint8_t)b, 0xff};
+ return {(uint8_t)r, (uint8_t)g, (uint8_t)b, 0x00};
```

The only place `ParseColor` is used is the following:

https://github.com/hzeller/timg/blob/cfd5f7a99401074ccfad31fa6234e94e5175074f/src/timg.cc#L758-L779

and with the above proposed change we can simplify the logic of this codeblock. For example if we are using a transparent background no need to query the terminal for a background pic.

This does remove user specified background though, since the opacity will always be 0, but that can be changed with reading the opacity value properly in the `ParseColor` method.

I can make a PR on this soon.

**Comment by hzeller** [comment] 2022-04-13 20:35
ah, ok. The whole point of this function though is to provide a way for the user to specify the background color.
So I think we just need to extend it to not only understand `#rrggbb` but `#rrggbbaa`

**Comment by acxz** [comment] 2022-04-13 20:46
Okay so basically I see two things here:

1) allow user to specify background opacity (new feature request)
2) fix proper use of background color with transparency (bug fix)

**Comment by acxz** [comment] 2022-04-13 21:28
I do have a solution but currently it is not working with the kitty protocol.
Can you point me to where the color is rendered for kitty?

**Comment by acxz** [comment] 2022-04-14 14:44
> extend it to not only understand #rrggbb but #rrggbbaa

I attempted this however, intermediary opacity values do not work, i.e if `aa` is `00` then the background is transparent (same as `-b none`) and if `aa` is any other value than the background is completely opaque, resulting in the same backgroud as `#rrggbb`. Therefore, I believe there would be no point in adding such a feature for users to specify transparent backgrounds via rgba.

I believe this is a non-issue and can be closed or maybe I just don't understand the issue properly.

**Comment by acxz** [comment] 2022-04-20 14:37
@hzeller can you provide comments to this issue?

Would are the requirements to close this issue?

**Comment by acxz** [comment] 2022-06-10 17:28
> None seems to respect the -b flag though.

Can you show an example as this did work for me.

If you post the actual SVG's which didn't work that would appreciated as well so that we can reproduce the issue.

**Comment by acxz** [comment] 2022-07-01 12:50
> This always shows a white background:

Can confirm, the svg file always renders a white background. However, when I convert the svg the png using `-b none` properly has transparency.

>  This never shows a background, regardless of the -b flag:

Can also confirm, converting from the svg to the png does give nominal behavior and it is possible to change the background.

Looks like SVG's are just not being read in/operated on properly like png files are.
A temporary solution to this issue is to then convert svg files to png files.

**Comment by hzeller** [comment] 2022-09-19 16:53
If `auto` is the problem, then maybe the query for your particular terminal does not work ? What is the terminal you're using ?

**Comment by acxz** [comment] 2022-09-19 16:55
Other SVG files work on the same terminal. I am using termite.

**Comment by hzeller** [comment] 2022-09-20 21:24
So, this should work now, can you test on your favorite transparent SVGs ?

**Comment by acxz** [comment] 2022-09-21 03:59
@hzeller thanks for the fix!
Tested it on all the problematic SVG files linked in this issue and timg displays them correctly!

**Comment by hzeller** [comment] 2022-09-21 04:02
Great to hear.
Fix was done by @lromor ; thanks Leonardo!

**Closed by hzeller** 2022-09-21 04:02 UTC
