### ISSUE TITLE
Grid parameter ignored for pdfs

### ISSUE THREAD

**Issue by xeruf** [hzeller/timg#94] opened 2022-11-20 00:50 UTC
<img width="681" alt="image" src="https://user-images.githubusercontent.com/13354331/202877549-89616aa6-2210-426b-89bb-54780996acca.png">

When previewing a pdf, the `--grid` parameter value is completely ignored.

**Comment by hzeller** [comment] 2022-11-20 01:33
Interesting, indeed.
The reason is, that a PDF is treated as single 'image' as it is a single file even though it has multiple sub-images.

This should probably be broken up and behave as if it was separate independent images that then nicely arrange in the grid.

**Comment by hzeller** [comment] 2022-11-20 02:19
Alright, should be fixed now.
Can you do a fresh `git pull`, recompile and test with your PDF ?

**Comment by xeruf** [comment] 2022-11-21 12:03
Thank you, works :)

Just a little thing, but that might also be the fault of `kitty` -
When I allow height overflow, there is a slight offset within the grid:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/13354331/203046773-daa34f12-c85f-46c3-8984-c515dc3883b6.png">

    timg --grid=2 Oceans\ \(D\)\ -\ Akkorde.pdf -W

Scrolled up:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/13354331/203048616-0634e61f-1da4-405f-bcc3-0c0c450d19b5.png">

**Comment by hzeller** [comment] 2022-11-21 19:24
I don't observe that with Kitty, but maybe the PDF has different page sizes ? I have to test for that situation and double check that `-W` works in these cases.

(BTW, if you add `--auto-crop` unnecessary whitespace around is cropped, so you might get less of the whitespace pixels using up space).

Re-opening now while investigation is going on to reproduce.

**Comment by xeruf** [comment] 2022-11-22 10:56
I am seeing this for any PDF with multiple pages, all A4, even with `auto-crop` enabled (which is a good hint, thank you :) )

**Comment by hzeller** [comment] 2024-01-26 02:35
So the problem here is, that if you have `-W`, a page might be longer than the terminal and have to scroll down a little.
but in the grid, the cursor needs to jump up to the next page.
Now, the way terminals work, they don't allow to jump the cursor beyond the top of the terminal. So if the previos page is a bit longer, the next page will only be displayed starting from the position it could jump to .. slightly down.

So there is nothing we can do about this here.

In the latest release ( https://github.com/hzeller/timg/releases/tag/v1.6.0 ), the resolution of the rendering has been improved. I typically can easily read PDS with `--grid=2x1 -U` or even `--grid=3x1` (also, it is faster).
So if you read PDFs a lot, this might be an interesting release for you.

**Closed by hzeller** 2024-01-26 02:35 UTC
